apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi-app
  template:
    metadata:
      labels:
        app: strapi-app
    spec:
      imagePullSecrets:
        - name: ghcr.io-pull-secret # Managed in the cluster
      containers:
        - name: strapi
          image: ghcr.io/code-specialist/api.code-specialist.com:7c06ad210ff1dde4fed54d5ae9fb5c7ed52a0c8f
          resources:
            requests:
              memory: "256Mi"
              cpu: "512m"
            limits:
              memory: "1024Mi"
              cpu: "2048m"
          ports:
            - containerPort: 1337
              name: http
          envFrom:
            - configMapRef:
                name: strapi-app-conf 
            - secretRef:
                name: strapi-app-secret # Managed by external secret


---
apiVersion: v1
kind: Service
metadata:
  name: strapi-app
spec:
  type: NodePort
  selector:
    app: strapi-app
  ports:
    - name: http
      protocol: TCP
      port: 1337
      nodePort: 31337 
      targetPort: http