# This doesnt work at all. The docs are garbage. Got to talk to Jonas (:
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: code-specialist-website
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-code-specialist
    kind: SecretStore
  target:
    name: secret-to-be-created
    creationPolicy: Owner
  data:
  - secretKey: strapi-app-secret
    remoteRef:
      key: aws/secretsmanager
      version: v1
      property: POSTGRES_PASSWORD
      decodingStrategy: Base64
  dataFrom:
  - extract:
      key: code-specialist-website-secrets