apiVersion: v1
kind: ConfigMap
metadata:
  name: strapi-postgres
data:
  POSTGRES_USER: strapi
  POSTGRES_DB: strapi-db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: strapi-app-conf
data:
  HOST: 0.0.0.0
  PORT: "1337"
  NODE_ENV: production
  DATABASE_HOST: strapi-db
  DATABASE_PORT: "5432"
  DATABASE_USERNAME: strapi
  DATABASE_NAME: strapi-db