name: Image build

on:
  push:
    branches:
      - master

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build the Strapi Docker Image
        run: >
          docker build
          --progress=plain
          --tag ghcr.io/code-specialist/api.code-specialist.com:${{ github.sha }}
          .

      - name: Push the image
        run: docker push